// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehdjbofvnlylmeymjxys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZGpib2Z2bmx5bG1leW1qeHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjIyNTYsImV4cCI6MjA2NDc5ODI1Nn0.UqrOHG7v0cTtoelOF31w8KlBSd0CzN5fOZydR2AU8zA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);